export const routes = {
  dashboard: "/dashboard",
  assets: "/assets",
  software: "/software",
  discovery: "/discovery",
  cloud: "/cloud",
  financial: "/financial",
  reports: "/reports",
  users: "/users",
  settings: "/settings",
  agentDashboard: "/agent/dashboard",
  agentAssets: "/agent/assets",
  agentTickets: "/agent/tickets",
  agentUsers: "/agent/users",
  agentInventory: "/agent/inventory",
  agentReports: "/agent/reports",
  agentSettings: "/agent/settings",
  superAdmin: "/super-admin",
  superCompanies: "/super-admin/companies",
  superSubscriptions: "/super-admin/subscriptions",
  superTenants: "/super-admin/tenants",
  superAdmins: "/super-admin/admins",
  superAudit: "/super-admin/audit",
  superSettings: "/super-admin/settings",
} as const;
